Firesphere\SolrSearch\Indexes\BaseIndex:
  extensions:
    - Firesphere\SolrFluent\FluentExtension # Fluent compatibility
Firesphere\SolrSearch\Services\SchemaService:
  extensions:
    - Firesphere\SolrFluent\FluentExtension
Firesphere\SolrSearch\Factories\DocumentFactory:
  extensions:
    - Firesphere\SolrFluent\FluentExtension
