Firesphere\SolrSearch\Indexes\BaseIndex:
  extensions:
    - Firesphere\SolrFluent\Extensions\FluentIndexExtension # Fluent compatibility
Firesphere\SolrSearch\Factories\SchemaFactory:
  extensions:
    - Firesphere\SolrFluent\Extensions\FluentSchemaExtension
Firesphere\SolrSearch\Factories\DocumentFactory:
  extensions:
    - Firesphere\SolrFluent\Extensions\FluentDocumentExtension
