Firesphere\SolrSearch\Indexes\BaseIndex:
  extensions:
    - Firesphere\SolrFluent\Extensions\FluentIndexExtension # Fluent compatibility
Firesphere\SolrSearch\Services\SchemaService:
  extensions:
    - Firesphere\SolrFluent\Extensions\FluentSchemaExtension
Firesphere\SolrSearch\Factories\DocumentFactory:
  extensions:
    - Firesphere\SolrFluent\Extensions\FluentDocumentExtension
